import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { DeviceTypeContextProvider } from "@/lib/hooks/useDeviceType";
import { RootLayoutClient } from "@/components/Layout/RootLayoutClient";
import { AuthProvider } from "@/lib/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <DeviceTypeContextProvider>
            <AuthProvider>
              <RootLayoutClient>{children}</RootLayoutClient>
            </AuthProvider>
          </DeviceTypeContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
